version: '3.8'
services:
  adelyn-blog-frontend:
    image: adelyn-blog-frontend:1.0.0
    container_name: adelyn-blog-frontend
    privileged: true
    volumes:
      - /docker/cert/blog.adelyn.cn.pem:/usr/local/nginx/conf/cert.pem
      - /docker/cert/blog.adelyn.cn.key:/usr/local/nginx/conf/cert.key
    ports:
      - "443:443"
    restart: always

networks:
  default:
    external:
      name: adelyn
